import * as React from 'react';
import type { Metadata } from 'next';

import { plusJakarta } from './font';
import { Providers } from './providers';
import './styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className='scroll-smooth' lang='en'>
      <body className={`${plusJakarta.className} text-dark-200`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
